# Generated by Django 5.0.3 on 2024-03-31 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_processor_videocard_laptop_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='cores',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='processor',
            name='frequency',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='videocard',
            name='core_clock',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='videocard',
            name='memory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.ForeignKey(on_delete=models.CASCADE, to='laptops.processor', null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='video_card',
            field=models.ForeignKey(on_delete=models.CASCADE, to='laptops.videocard', null=True),
        ),
    ]
