# Generated by Django 5.0.3 on 2024-03-31 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_processor_cores_processor_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laptops.processor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='video_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laptops.videocard'),
            preserve_default=False,
        ),
    ]
