# Generated by Django 5.0.3 on 2024-03-31 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_laptop_user_alter_laptop_processor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laptops.processor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='video_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laptops.videocard'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FavoriteLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.laptop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_laptops', through='laptops.FavoriteLaptop', to=settings.AUTH_USER_MODEL),
        ),
    ]
