# Generated by Django 5.0.3 on 2024-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0005_alter_laptop_processor_alter_laptop_video_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritelaptop',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
